"""Database infrastructure layer for managing connections and mapping relational schemas.

This module encapsulates SQLAlchemy connection pooling, maps application models to
physical tables, and exposes transactional sessions to downstream pipelines.
"""

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    create_engine,
    func,
)
from sqlalchemy.orm import declarative_base, sessionmaker

from sciforge.matkit.utils.config import Config

Base = declarative_base()


class MaterialModel(Base):
    """SQLAlchemy object-relational mapping for tracking material physical properties.

    Maps physical constraints fetched from external discovery APIs onto the relational
    schema structure to act as analytical baselines.

    Attributes:
        material_id (str): Primary key identifier string (e.g., 'mp-100').
        formula (str): Reducible chemical formula string identifier.
        space_group (int): Crystallographic international space group number.
        effective_mass_me (float): Relative electron effective mass curvature value.
        permittivity (float): Relative macroscopic static material dielectric permittivity.
        created_at (datetime): Chronological insert timestamp generated by the database.
    """

    __tablename__ = "materials"

    material_id = Column(String(50), primary_key=True)
    formula = Column(String(20), nullable=False)
    space_group = Column(Integer, nullable=False)
    effective_mass_me = Column(Float, nullable=False)
    permittivity = Column(Float, nullable=False)


class DatabaseClient:
    """Manages connection lifecycles and transactional operations for the data store.

    Establishes a thread-safe connection pool using connection parameters pulled from system
    environment configurations.
    """

    def __init__(self) -> None:
        """Initialises the database engine and configures transactional session factories."""
        self.engine = create_engine(
            Config.DB_URL, pool_size=5, max_overflow=10, pool_pre_ping=True
        )
        self.SessionLocal = sessionmaker(
            bind=self.engine, autoflush=False, autocommit=False
        )

    def create_tables(self) -> None:
        """Generates all structural physical tables mapped via SQLAlchemy models if missing."""
        Base.metadata.create_all(bind=self.engine)

    def get_session(self):
        """Returns a managed database session instance context wrapper.

        Returns:
            Session: A local transactional database session instance.
        """
        return self.SessionLocal()


class SimulationRegistryModel(Base):
    """SQLAlchemy object-relational mapping for tracking PINN training metrics and artifacts.

    Acts as an immutable operational ledger logging hyperparameters, convergence constraints,
    and references to the structural model export files.

    Attributes:
        run_id (int): Automatically incremented unique execution primary key identifier.
        material_id (str): Foreign key linking back to the matching entry in the materials table.
        engine_mode (str): Flag defining the physics module style chosen ('constant'/'coupled').
        epochs_trained (int): Complete optimisation step iteration boundaries executed.
        learning_rate (float): Active step optimisation size scalar coefficient.
        final_total_loss (float): Aggregate system minimisation loss at the final epoch step.
        final_bc_loss (float): Boundary condition error metrics calculated at runtime exit.
        final_physics_loss (float): Physical residual calculus errors recorded at execution.
        execution_time_seconds (float): Absolute duration processing bounds tracking execution.
        model_artifact_path (str): Relative system storage destination mapping the ONNX export file.
        created_at (datetime): Chronological registration timestamp generated by PostgreSQL.
    """

    __tablename__ = "carrier_pinn_simulation_registry"

    run_id: Column = Column(Integer, primary_key=True, autoincrement=True)
    material_id: Column = Column(
        String(50),
        ForeignKey("materials.material_id", ondelete="CASCADE"),
        nullable=False,
    )
    engine_mode: Column = Column(String(20), nullable=False)
    epochs_trained: Column = Column(Integer, nullable=False)
    learning_rate: Column = Column(Float, nullable=False)
    final_total_loss: Column = Column(Float, nullable=False)
    final_bc_loss: Column = Column(Float, nullable=False)
    final_physics_loss: Column = Column(Float, nullable=False)
    execution_time_seconds: Column = Column(Float, nullable=False)
    model_artifact_path: Column = Column(String(512), nullable=False)
    created_at: Column = Column(DateTime, server_default=func.now())
