"""Database infrastructure layer for managing connections and mapping relational schemas.

This module encapsulates SQLAlchemy connection pooling, maps application models to
physical tables, and exposes transactional sessions to downstream pipelines.
"""

from sqlalchemy import Column, Float, Integer, String, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

from sciforge.matkit.utils.config import Config

Base = declarative_base()


class MaterialModel(Base):
    """SQLAlchemy object-relational mapping for tracking material physical properties.

    Maps physical constraints fetched from external discovery APIs onto the relational
    schema structure to act as analytical baselines.

    Attributes:
        material_id (str): Primary key identifier string (e.g., 'mp-100').
        formula (str): Reducible chemical formula string identifier.
        space_group (int): Crystallographic international space group number.
        effective_mass_me (float): Relative electron effective mass curvature value.
        permittivity (float): Relative macroscopic static material dielectric permittivity.
        created_at (datetime): Chronological insert timestamp generated by the database.
    """

    __tablename__ = "materials"

    material_id = Column(String(50), primary_key=True)
    formula = Column(String(20), nullable=False)
    space_group = Column(Integer, nullable=False)
    effective_mass_me = Column(Float, nullable=False)
    permittivity = Column(Float, nullable=False)


class DatabaseClient:
    """Manages connection lifecycles and transactional operations for the data store.

    Establishes a thread-safe connection pool using connection parameters pulled from system
    environment configurations.
    """

    def __init__(self) -> None:
        """Initialises the database engine and configures transactional session factories."""
        self.engine = create_engine(Config.DB_URL, pool_size=5, max_overflow=10)
        self.SessionLocal = sessionmaker(
            bind=self.engine, autoflush=False, autocommit=False
        )

    def create_tables(self) -> None:
        """Generates all structural physical tables mapped via SQLAlchemy models if missing."""
        Base.metadata.create_all(bind=self.engine)

    def get_session(self):
        """Returns a managed database session instance context wrapper.

        Returns:
            Session: A local transactional database session instance.
        """
        return self.SessionLocal()
